A contact page has been created
GSG-FC02/GalleryNSM pull request #17
Opened 2021-03-02 21:51 UTC by sajarantisi

Relates #10

2021-03-03 00:23 UTC, majed1992 submitted a review, later dismissed

2021-03-03 08:20 UTC, Nour-Nasr requested changes
fix the landing page background image by writing the code below : 
.landingPage {
   background-image: url("/images/background.png");
    background-color:#F7F3F3;
    margin-bottom: 100px;
    background-attachment: fixed;

}

2021-03-04 09:19 UTC, sajarantisi reviewed
👍

2021-03-04 15:37 UTC, AlaaTaima approved these changes

2021-03-04 15:37 UTC, merged